#!/usr/local/bin/python3

import time
import subprocess


# COLORS (italic)
BLACK  = '\033[3;30m'
RED = '\033[3;31m'
GREEN = '\033[3;32m'
YELLOW = '\033[3;33m'
PURPLE = '\033[3;34m'
MAGENTA = '\033[3;35m'
CYAN = '\033[3;36m'
WHITE = '\033[3;37m'
NC = '\033[0m' # NC = NO COLOR (reset)

FILE_COLOR = YELLOW

print(FILE_COLOR + '[wrong config file: fake_file_lol]' + NC)
subprocess.run(['../webserv', '../conf/error_config/fake_file_lol'])
print('[ \033[0;32mOK\033[0m ]')

time.sleep(0.5)
print('----------------------------------')

print(FILE_COLOR + '[no config file]' + NC)
subprocess.run(['../webserv'])
print('[ \033[0;32mOK\033[0m ]')

time.sleep(0.5)
print('----------------------------------')

print(FILE_COLOR + '[config_autoindexOff_noIndex.conf]' + NC)
subprocess.run(['../webserv', '../conf/error_config/config_autoindexOff_noIndex.conf'])
print('[ \033[0;32mOK\033[0m ]')

time.sleep(0.5)
print('----------------------------------')

print(FILE_COLOR + '[config_embedded_servers.conf]' + NC)
subprocess.run(['../webserv', '../conf/error_config/config_embedded_servers.conf'])
print('[ \033[0;32mOK\033[0m ]')

time.sleep(0.5)
print('----------------------------------')

time.sleep(0.5)
print(FILE_COLOR + '[config_empty.conf]' + NC)
subprocess.run(['../webserv', '../conf/error_config/config_empty.conf'])
print('[ \033[0;32mOK\033[0m ]')

time.sleep(0.5)
print('----------------------------------')

print(FILE_COLOR + '[config_lonely_bracket.conf]' + NC)
subprocess.run(['../webserv', '../conf/error_config/config_lonely_bracket.conf'])
print('[ \033[0;32mOK\033[0m ]')

time.sleep(0.5)
print('----------------------------------')

print(FILE_COLOR + '[config_missing_bracket.conf]' + NC)
subprocess.run(['../webserv', '../conf/error_config/config_missing_bracket.conf'])
print('[ \033[0;32mOK\033[0m ]')

time.sleep(0.5)
print('----------------------------------')

print(FILE_COLOR + '[config_no_default_location.conf]' + NC)
subprocess.run(['../webserv', '../conf/error_config/config_no_default_location.conf'])
print('[ \033[0;32mOK\033[0m ]')

time.sleep(0.5)
print('----------------------------------')

print(FILE_COLOR + '[config_no_location.conf]' + NC)
subprocess.run(['../webserv', '../conf/error_config/config_no_location.conf'])
print('[ \033[0;32mOK\033[0m ]')


time.sleep(0.5)
print('----------------------------------')

print(FILE_COLOR + '[config_no_such_directive.conf]' + NC)
subprocess.run(['../webserv', '../conf/error_config/config_no_such_directive.conf'])
print('[ \033[0;32mOK\033[0m ]')

time.sleep(0.5)
print('----------------------------------')

time.sleep(0.5)
print(FILE_COLOR + '[config_outside_server_directive.conf]' + NC)
subprocess.run(['../webserv', '../conf/error_config/config_outside_server_directive.conf'])
print('[ \033[0;32mOK\033[0m ]')

time.sleep(0.5)
print('----------------------------------')

time.sleep(0.5)
print(FILE_COLOR + '[config_random_data.conf]' + NC)
subprocess.run(['../webserv', '../conf/error_config/config_outside_server_directive.conf'])
print('[ \033[0;32mOK\033[0m ]')

time.sleep(0.5)
print('----------------------------------')

time.sleep(0.5)
print(FILE_COLOR + '[config_redir_root_and_absolutePath.conf]' + NC)
subprocess.run(['../webserv', '../conf/error_config/config_redir_root_and_absolutePath.conf'])
print('[ \033[0;32mOK\033[0m ]')

time.sleep(0.5)
print('----------------------------------')

time.sleep(0.5)
print(FILE_COLOR + '[config_tooBigMaxBodySize.conf]' + NC)
subprocess.run(['../webserv', '../conf/error_config/config_tooBigMaxBodySize.conf'])
print('[ \033[0;32mOK\033[0m ]')

time.sleep(0.5)
print('----------------------------------')

time.sleep(0.5)
print(FILE_COLOR + '[config_wrongMaxBodySize.conf]' + NC)
subprocess.run(['../webserv', '../conf/error_config/config_wrongMaxBodySize.conf'])
print('[ \033[0;32mOK\033[0m ]')

time.sleep(0.5)
print('----------------------------------')
